language: go
go:
- "1.12"
os:
- linux
install: make travis-setup
script: make travis-release
deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash /dev/stdin --rm-dist
  skip_cleanup: true
  on:
    tags: true
    repo: kopia/kopia
git:
  depth: 9999999
env:
  - GO111MODULE=on
