language: go
go:
- '1.11'
os:
- linux
before_install:
- openssl aes-256-cbc -K $encrypted_0098ef8519ef_key -iv $encrypted_0098ef8519ef_iv
  -in test_service_account.json.enc -out storage/gcs/test_service_account.json -d
- make setup
script: make travis
