name: Endurance Test
on:
  push:
    branches: [ master ]
    tags:
      - v*
  schedule:
    # run on Mondays at 8AM
    - cron:  '0 8 * * 1'
jobs:
  endurance-test:
    name: Endurance Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go.
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Endurance Tests
      run: make endurance-tests
